import type { Metadata } from 'next'
import '@/assets/styles/tailwindcss.css'
import { ReactNode } from 'react'
import Providers from '@/providers/Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`bg-dark size-full`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
